apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway.yaml # Logical entry point to the Datum Gateway
  - routes-electricsql.yaml # Routes are how we bind the Gateway frontend to the Backend Endpoint
  - routes-frontend.yaml
  - endpoints.yaml

