apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: electricsql

resources:
  - workload.yaml

patches:
  - target:
      kind: Location
    patch: |
      - op: replace
        path: /spec/provider/gcp/projectId
        value: datum-dev-playground-1