apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - export.yaml

secretGenerator:
  - name: grafana-cloud-credentials
    options:
      disableNameSuffixHash: true
    type: kubernetes.io/basic-auth
    literals:
      - username=$USERNAME
      - password=$PASSWORD